name: HeroLeague
version: 1.0.0
main: de.herrbockwurst.heroleague.Main
description: HeroLeague
author: HerrBockwurst
commands:
  setcoord:
    usage: /<command> <lobby/rot/blau>
    description: Setzt Koordinatens
    aliases: [setcd]