name: Hero League
version: 1.0.0
main: de.herrbockwurst.heroleague.Main
description: Hero League
author: HerrBockwurst
commands:
  hub:
    usage: /<command> <lobby/rot/blau>
    description: Setzt Koordinatens
    aliases: [setcd]